name: CI

on:
  push:
    branches: [ test_ci ]
  pull_request:
    branches: [ test_ci ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    container: node:16-buster-slim
    defaults:
      run:
        shell: bash
    steps:
    - name: Upgrade packages
      run: |
        apt-get update 1>&2
        apt-get upgrade -y 1>&2
    - name: Install git
      run: |
        apt-get install git -y
    - name: Install Wine
      run: |
        dpkg --add-architecture i386 1>&2
        apt-get update 1>&2
        apt-get upgrade -y 1>&2
        apt install --install-recommends wine wine32 wine64 wine64-tools -y 1>&2
    - name: Install display dependencies
      run: |
        apt-get install xvfb libgl1-mesa-glx libgl1-mesa-glx:i386 libgl1:i386 libglx-mesa0:i386 libgl1-mesa-dri:i386 unzip fonts-liberation openbox x11-utils -y 1>&2
    - name: Setup display environment
      run: |
        Xvfb :2 & 1>&2
        export DISPLAY=:2
        while ! xdpyinfo; do sleep 1; jobs 1 || exit 1; done
        openbox & 1>&2
        echo "DISPLAY=:2" >> "$GITHUB_ENV"
    - name: Setup Wine environment
      run: |
        echo "WINEPREFIX=$RUNNER_TEMP/.wineprefix" >> "$GITHUB_ENV"
    - name: Setup Wine
      run: |
        wineserver -p
        wineboot -e
        wineserver -k
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          submodules: recursive
