name: CI

on:
  push:
    branches: [ test_ci ]
  pull_request:
    branches: [ test_ci ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    container: node:16-buster-slim
    defaults:
      run:
        shell: bash
    steps:
    - name: Upgrade packages
      run: |
        sudo apt-get update 1>&2
        sudo apt-get upgrade -y 1>&2
    - name: Install git
      run: |
        sudo apt-get install git
    - name: Install Wine
      run: |
        sudo dpkg --add-architecture i386 1>&2
        sudo apt-get update 1>&2
        sudo apt-get upgrade -y 1>&2
        sudo apt install --install-recommends wine wine32 wine64 wine64-tools -y 1>&2
    - name: Install display dependencies
      run: |
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt install xvfb libgl1-mesa-glx libgl1-mesa-glx:i386 libgl1:i386 libglx-mesa0:i386 libgl1-mesa-dri:i386 unzip ttf-mscorefonts-installer openbox x11-utils -y 1>&2
    - name: Setup display environment
      run: |
        Xvfb :2 & 1>&2
        export DISPLAY=:2
        while ! xdpyinfo; do sleep 1; jobs 1 || exit 1; done
        openbox & 1>&2
        echo "DISPLAY=:2" >> "$GITHUB_ENV"
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          submodules: recursive
